export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
